### ISSUE TITLE
Having Issues with Obdython

### ISSUE THREAD

**Issue by jeffjet24** [souvik1997/obdython#2]
Hello, I am working on a project just like yours with picard. I loved your project and am really excited to get mine going. :) However, I am running into an issue with getting BADDATA errors for all of the different sensors (even 'pids'). I did some troubleshooting, and in the function interpret_result(), at line 117 in **init**.py, the value of 'code' is BUSINIT:...ERROR. This happens for any value that I try to retrieve from the car. Could you possibly point me in a direction to solve the issue?

Here is my setup that I have, to help you understand how I have things set up. 

My OBDII Reader: http://amzn.to/1IzkLGC 

Raspberry Pi running Raspbian with python 3 installed.
I have installed obdython as a package for python
I had moved the recorder.py script to /etc/recorder/ on my system
The script is being run as root. 

My script to run the recorder.py:
# !/bin/bash
# checking to make sure that the time server has been started

/etc/inid.d/ntp start
# moving to location of the script

cd /etc/recorder
# calling the python script

python3 recorder.py -d bluetooth -m 00:0D:18:3A:67:89 -c 1 -r pids rpm fuel_status load speed -o /logging/output.csv

I am getting lights from the bluetooth obd reader, indicating that it is communicating with my pi. 

Here is an excerpt from my csv file, it probably wont be much use though, it just says bad data...

time,rpm,fuel_status,load,speed
11.323777198791504,BADDATA,BADDATA,BADDATA,BADDATA
22.682969093322754,BADDATA,BADDATA,BADDATA,BADDATA
34.01432800292969,BADDATA,BADDATA,BADDATA,BADDATA

Let me know if there is anymore info that I can provide.

Thanks for your help
Jeffjet24

**Comment by souvik1997** [comment]
Thank you for your interest in my project. Have you tried testing the OBD-II adapter with an smartphone app? I used Torque (the free version) for Android. If Torque lets you view the engine data it could be something as simple as a formatting issue (such as an extra newline or spaces). You could try sticking a few print() statements into obdython to debug further. 

Additionally, since the adapter you are using is different from the one I used, there might be a few differences in how the adapter translates ECU output. I don't recall encountering the error "BUSINIT". Try connecting directly to the adapter using minicom or screen with a serial connection. Here is nice tutorial on how to do this: http://gersic.com/connecting-your-raspberry-pi-to-a-bluetooth-obd-ii-adapter/

**Comment by jeffjet24** [comment]
I gave the Torque free Android app a shot, even after pairing with my OBD reader, it was reporting no data from it either. The OBD reader that I got was from a friend, and he has had it for a while now, I think the adapter is shot. I am gonna try a different adapter and see how that goes. 

Just for fun while I wait for the new one, I will try connecting to the adapter directly and see if it returns any useful data. 

Thanks!

**Comment by jeffjet24** [comment]
After trying a few different bluetooth OBD adapters and other configurations with my pi, I was able to access values from the adapter directly, and from Torque as well. I went ahead and tried obdython again, and it worked! I think this issue can be closed. Thanks for you help in pointing me in the right direction! 

I addition to what you did in your project, I added a RTC to my pi, so then the time would remain correct. Rather than going through a computer, I have a mobile hotspot in my car, and the pi then sends the csv file to my server at home. Once I get everything set up and the data flowing in, I plan to analyze the data using R, and plot it in a shiny web app (shiny.rstudio.com).

Let me know if you want to know more details on the other things that I did, in case you want to add it to your set up.
